### PR TITLE
System diagrams and architectural design.

### LINKED ISSUE #1: Provide architectural diagram

### PR DESCRIPTION
**Pull request by tommasobertoni**
Updated README with diagrams and architectural design.

Closes #1

### CODE REVIEW

**Comment by tziemek** [comment]
Why has the yellow service a dependency on the red service?

**Comment by tommasobertoni** [comment]
The yellow service depends on the `OrderRatesSelected` event published by the red service, in order to copy the amounts (rate, cancellation fee...), and be independent in subsequent operations (i.e. payments).

**Comment by tziemek** [comment]
Ah yes, I haven't seen the descriptions of our events in the klaxoon board. Now I see them again oO

Another thing:
Do we really need ambassadors? I think an SDK would be enough at the moment. I don't see the benefit of an ambassador here, especially if it is provided by each service (we don't reduce schema coupling then).

**Comment by tziemek** [comment]
And If we count the `OrderRatesSelected` event, then we should count the other events too and add the other outgoing dependencies too. Or is `OrderRatesSelected` different than i.e. `RequestedRoomTypeReserved` (Yellow -> Blue)?

**Comment by tommasobertoni** [comment]
In the last design draft we discussed about elevating the purple service as an orchestrator for the booking process in order to reduce the (double) coupling between the yellow and blue service (and also the logical coupling to the UI).

The purple service would listen to events from yellow/blue and send commands to them appropriately, defining the completion or failure of the booking process.
With this configuration, blue and yellow are also unaware of purple, hence the one-directional arrows.

_y_ `CancellationFeeAuthorizationAcquired e1 ->`
_p_ `e1 -> send(RequestedRoomTypeReserved) c1 ->`
_b_ `c1 -> RequestedRoomTypeReserved e2 ->`
_p_ `e2 -> send(ChargeCancellationFee) c2 ->`
...

**Comment by tziemek** [comment]
Let's discuss that again for a few minutes in the next meeting.

**Review by tziemek — APPROVED** [review]

**Review by tziemek — APPROVED** [review]
lgtm

**Pull request merged**
