### PR TITLE
Updates README links.

### PR DESCRIPTION
**Pull request by tommasobertoni**
Updates discussions from team to repo.
Adds project structure and meeting notes links.
Removes MIT-LICENSE badge.

### CODE REVIEW

**Review by tziemek — APPROVED** [review]
lgtm

**Comment by tobias-tengler** [comment]
I would prefer a regular TOC actually...

**Comment by tommasobertoni** [comment]
@tobias-tengler how would it look like?
These are out-of-readme links

**Comment by tobias-tengler** [comment]
> @tobias-tengler how would it look like?
> These are out-of-readme links

Oh I just checked and the Github Markdown flavor doesn't even support TOC.
Maybe something without any special formatting, just:
### Documentation
[File 1](/docs/file_1.md)
[File 2](/docs/file_2.md)
[File 3](/docs/file_3.md)

I just find it way more readable, especially if the number of docs grows. The badges are just too 'noisy' for me personally. But if you all prefer those, go for it ^^

**Comment by tziemek** [comment]
At first I didn't really care about the badges, but the more I think about it, they don't look good for that purpose. I would now lean to the old approach and use badges only for builds (if we have some) and such stuff.

**Comment by tommasobertoni** [comment]
Do we want all/more/less links?

[Requirements]()
[Discussions]()
[How to Run]()
[Project Structure]()
[Meeting Notes]()

**Review by tziemek — APPROVED** [review]

**Review by tobias-tengler — APPROVED** [review]

**Pull request merged**
